server:
  port: 8081

spring:
  application:
    name: SECURITY-AUTH-SERVER
  redis:
    host: localhost
    port: 6379
    password: root

eureka:
  instance:
    # 向Eureka 服务端发送心跳的间隔时间，单位为秒，用于服务续约
    lease-renewal-interval-in-seconds: 30
  client:
    # 为true时表示将当前服务注册到Eureka服务端
    register-with-eureka: true
    # 为true时表示从Eureka 服务端获取注册的服务信息
    fetch-registry: true
    # 新实例信息的变化到Eureka服务端的间隔时间，单位为秒
    registry-fetch-interval-seconds: 30
    # 默认值为30秒，即每30秒去Eureka服务端上获取服务并缓存,实际可以指定为默认值即可
    instance-info-replication-interval-seconds: 30
    service-url:
      defaultZone: http://admin:admin-eureka@localhost:8761/register/eureka
